export const RoleCode = {
  ADMIN: 'ADMIN',
  FACULTY: 'FACULTY',
  STAFF: 'STAFF',
  SUPER_ADMIN: 'SUPER_ADMIN',
  APPOINTMENT_ADMIN: 'APPOINTMENT_ADMIN',
  OFFICIAL: 'OFFICIAL',
  PA: 'PA',
  EA: 'EA',
  RECEPTION: 'RECEPTION',
  SECURITY: 'SECURITY',
  EMPLOYEE: 'EMPLOYEE',
  GUEST: 'GUEST',
  AUDITOR: 'AUDITOR',
} as const;
export type RoleCode = (typeof RoleCode)[keyof typeof RoleCode];

export const PROJECT_ROLES = [
  RoleCode.ADMIN,
  RoleCode.FACULTY,
  RoleCode.STAFF,
] as const;

export const Scope = {
  OWN: 'OWN',
  ASSIGNED: 'ASSIGNED',
  ORG: 'ORG',
} as const;
export type Scope = (typeof Scope)[keyof typeof Scope];

export const Permission = {
  APPOINTMENT_CREATE: 'appointment.create',
  APPOINTMENT_READ: 'appointment.read',
  APPOINTMENT_REVIEW: 'appointment.review',
  APPOINTMENT_APPROVE: 'appointment.approve',
  APPOINTMENT_RESCHEDULE: 'appointment.reschedule',
  APPOINTMENT_CANCEL: 'appointment.cancel',
  APPOINTMENT_SET_URGENT: 'appointment.set_urgent',
  APPOINTMENT_START: 'appointment.start',
  APPOINTMENT_COMPLETE: 'appointment.complete',
  APPOINTMENT_CLOSE: 'appointment.close',

  CALENDAR_READ: 'calendar.read',
  CALENDAR_WRITE: 'calendar.write',
  CALENDAR_READ_PERSONAL: 'calendar.read_personal',
  CALENDAR_WRITE_PERSONAL: 'calendar.write_personal',

  AVAILABILITY_MANAGE: 'availability.manage',
  OFFICIAL_MANAGE: 'official.manage',
  SUPPORT_STAFF_MANAGE: 'support_staff.manage',
  DELEGATION_MANAGE: 'delegation.manage',

  ROOM_READ: 'room.read',
  ROOM_MANAGE: 'room.manage',
  VISIT_READ: 'visit.read',
  VISIT_CHECKIN: 'visit.checkin',
  VISIT_CHECKOUT: 'visit.checkout',
  VISIT_DENY: 'visit.deny',

  TASK_READ: 'task.read',
  TASK_WRITE: 'task.write',
  TASK_ASSIGN: 'task.assign',
  TASK_EXPORT: 'task.export',

  NOTE_READ: 'note.read',
  NOTE_WRITE: 'note.write',

  REPORT_READ: 'report.read',
  AUDIT_READ: 'audit.read',
  USER_MANAGE: 'user.manage',
  ROLE_MANAGE: 'role.manage',
  SETTINGS_MANAGE: 'settings.manage',
  HOLIDAY_MANAGE: 'holiday.manage',
} as const;
export type Permission = (typeof Permission)[keyof typeof Permission];

export interface RolePermissionMapping {
  permission: Permission;
  scope: Scope;
}

/**
 * Standard Role Matrix (§6.3)
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<RoleCode, RolePermissionMapping[]> = {
  [RoleCode.SUPER_ADMIN]: [
    { permission: Permission.APPOINTMENT_CREATE, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_READ, scope: Scope.ORG },
    { permission: Permission.CALENDAR_READ, scope: Scope.ORG },
    { permission: Permission.AVAILABILITY_MANAGE, scope: Scope.ORG },
    { permission: Permission.OFFICIAL_MANAGE, scope: Scope.ORG },
    { permission: Permission.SUPPORT_STAFF_MANAGE, scope: Scope.ORG },
    { permission: Permission.DELEGATION_MANAGE, scope: Scope.ORG },
    { permission: Permission.ROOM_READ, scope: Scope.ORG },
    { permission: Permission.ROOM_MANAGE, scope: Scope.ORG },
    { permission: Permission.REPORT_READ, scope: Scope.ORG },
    { permission: Permission.AUDIT_READ, scope: Scope.ORG },
    { permission: Permission.USER_MANAGE, scope: Scope.ORG },
    { permission: Permission.ROLE_MANAGE, scope: Scope.ORG },
    { permission: Permission.SETTINGS_MANAGE, scope: Scope.ORG },
    { permission: Permission.HOLIDAY_MANAGE, scope: Scope.ORG },
  ],
  [RoleCode.ADMIN]: [
    { permission: Permission.APPOINTMENT_CREATE, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_READ, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_REVIEW, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_APPROVE, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_RESCHEDULE, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_CANCEL, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_SET_URGENT, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_START, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_COMPLETE, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_CLOSE, scope: Scope.ORG },
    { permission: Permission.CALENDAR_READ, scope: Scope.ORG },
    { permission: Permission.CALENDAR_WRITE, scope: Scope.ORG },
    { permission: Permission.AVAILABILITY_MANAGE, scope: Scope.ORG },
    { permission: Permission.OFFICIAL_MANAGE, scope: Scope.ORG },
    { permission: Permission.SUPPORT_STAFF_MANAGE, scope: Scope.ORG },
    { permission: Permission.DELEGATION_MANAGE, scope: Scope.ORG },
    { permission: Permission.ROOM_READ, scope: Scope.ORG },
    { permission: Permission.ROOM_MANAGE, scope: Scope.ORG },
    { permission: Permission.VISIT_READ, scope: Scope.ORG },
    { permission: Permission.VISIT_CHECKIN, scope: Scope.ORG },
    { permission: Permission.VISIT_CHECKOUT, scope: Scope.ORG },
    { permission: Permission.VISIT_DENY, scope: Scope.ORG },
    { permission: Permission.TASK_READ, scope: Scope.ORG },
    { permission: Permission.TASK_WRITE, scope: Scope.ORG },
    { permission: Permission.TASK_ASSIGN, scope: Scope.ORG },
    { permission: Permission.TASK_EXPORT, scope: Scope.ORG },
    { permission: Permission.NOTE_READ, scope: Scope.ORG },
    { permission: Permission.NOTE_WRITE, scope: Scope.ORG },
    { permission: Permission.REPORT_READ, scope: Scope.ORG },
    { permission: Permission.AUDIT_READ, scope: Scope.ORG },
    { permission: Permission.USER_MANAGE, scope: Scope.ORG },
    { permission: Permission.ROLE_MANAGE, scope: Scope.ORG },
    { permission: Permission.SETTINGS_MANAGE, scope: Scope.ORG },
    { permission: Permission.HOLIDAY_MANAGE, scope: Scope.ORG },
  ],
  [RoleCode.FACULTY]: [
    { permission: Permission.APPOINTMENT_CREATE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_READ, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_REVIEW, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_APPROVE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_RESCHEDULE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_CANCEL, scope: Scope.OWN },
    { permission: Permission.CALENDAR_READ, scope: Scope.OWN },
    { permission: Permission.CALENDAR_WRITE, scope: Scope.OWN },
    { permission: Permission.AVAILABILITY_MANAGE, scope: Scope.OWN },
    { permission: Permission.TASK_READ, scope: Scope.OWN },
    { permission: Permission.TASK_WRITE, scope: Scope.OWN },
  ],
  [RoleCode.APPOINTMENT_ADMIN]: [
    { permission: Permission.APPOINTMENT_CREATE, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_READ, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_REVIEW, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_RESCHEDULE, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_CANCEL, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_SET_URGENT, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_START, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_COMPLETE, scope: Scope.ORG },
    { permission: Permission.APPOINTMENT_CLOSE, scope: Scope.ORG },
    { permission: Permission.CALENDAR_READ, scope: Scope.ORG },
    { permission: Permission.CALENDAR_WRITE, scope: Scope.ORG },
    { permission: Permission.AVAILABILITY_MANAGE, scope: Scope.ORG },
    { permission: Permission.OFFICIAL_MANAGE, scope: Scope.ORG },
    { permission: Permission.SUPPORT_STAFF_MANAGE, scope: Scope.ORG },
    { permission: Permission.DELEGATION_MANAGE, scope: Scope.ORG },
    { permission: Permission.ROOM_READ, scope: Scope.ORG },
    { permission: Permission.ROOM_MANAGE, scope: Scope.ORG },
    { permission: Permission.VISIT_READ, scope: Scope.ORG },
    { permission: Permission.VISIT_CHECKIN, scope: Scope.ORG },
    { permission: Permission.VISIT_CHECKOUT, scope: Scope.ORG },
    { permission: Permission.REPORT_READ, scope: Scope.ORG },
    { permission: Permission.HOLIDAY_MANAGE, scope: Scope.ORG },
  ],
  [RoleCode.OFFICIAL]: [
    { permission: Permission.APPOINTMENT_CREATE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_READ, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_REVIEW, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_APPROVE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_RESCHEDULE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_CANCEL, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_SET_URGENT, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_START, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_COMPLETE, scope: Scope.OWN },
    { permission: Permission.CALENDAR_READ, scope: Scope.OWN },
    { permission: Permission.CALENDAR_WRITE, scope: Scope.OWN },
    { permission: Permission.CALENDAR_READ_PERSONAL, scope: Scope.OWN },
    { permission: Permission.CALENDAR_WRITE_PERSONAL, scope: Scope.OWN },
    { permission: Permission.AVAILABILITY_MANAGE, scope: Scope.OWN },
    { permission: Permission.DELEGATION_MANAGE, scope: Scope.OWN },
    { permission: Permission.TASK_READ, scope: Scope.OWN },
    { permission: Permission.TASK_WRITE, scope: Scope.OWN },
    { permission: Permission.TASK_ASSIGN, scope: Scope.OWN },
    { permission: Permission.TASK_EXPORT, scope: Scope.OWN },
    { permission: Permission.NOTE_READ, scope: Scope.OWN },
    { permission: Permission.NOTE_WRITE, scope: Scope.OWN },
    { permission: Permission.REPORT_READ, scope: Scope.OWN },
  ],
  [RoleCode.PA]: [
    { permission: Permission.APPOINTMENT_CREATE, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_READ, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_REVIEW, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_APPROVE, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_RESCHEDULE, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_CANCEL, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_SET_URGENT, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_START, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_COMPLETE, scope: Scope.ASSIGNED },
    { permission: Permission.CALENDAR_READ, scope: Scope.ASSIGNED },
    { permission: Permission.CALENDAR_WRITE, scope: Scope.ASSIGNED },
    { permission: Permission.AVAILABILITY_MANAGE, scope: Scope.ASSIGNED },
    { permission: Permission.VISIT_READ, scope: Scope.ASSIGNED },
    { permission: Permission.VISIT_CHECKIN, scope: Scope.ASSIGNED },
    { permission: Permission.VISIT_CHECKOUT, scope: Scope.ASSIGNED },
    { permission: Permission.TASK_READ, scope: Scope.ASSIGNED },
    { permission: Permission.TASK_WRITE, scope: Scope.ASSIGNED },
    { permission: Permission.TASK_ASSIGN, scope: Scope.ASSIGNED },
    { permission: Permission.TASK_EXPORT, scope: Scope.ASSIGNED },
    { permission: Permission.NOTE_READ, scope: Scope.ASSIGNED },
    { permission: Permission.NOTE_WRITE, scope: Scope.ASSIGNED },
    { permission: Permission.REPORT_READ, scope: Scope.ASSIGNED },
  ],
  [RoleCode.EA]: [
    { permission: Permission.APPOINTMENT_CREATE, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_READ, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_REVIEW, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_APPROVE, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_RESCHEDULE, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_CANCEL, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_SET_URGENT, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_START, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_COMPLETE, scope: Scope.ASSIGNED },
    { permission: Permission.CALENDAR_READ, scope: Scope.ASSIGNED },
    { permission: Permission.CALENDAR_WRITE, scope: Scope.ASSIGNED },
    { permission: Permission.AVAILABILITY_MANAGE, scope: Scope.ASSIGNED },
    { permission: Permission.VISIT_READ, scope: Scope.ASSIGNED },
    { permission: Permission.VISIT_CHECKIN, scope: Scope.ASSIGNED },
    { permission: Permission.VISIT_CHECKOUT, scope: Scope.ASSIGNED },
    { permission: Permission.TASK_READ, scope: Scope.ASSIGNED },
    { permission: Permission.TASK_WRITE, scope: Scope.ASSIGNED },
    { permission: Permission.TASK_ASSIGN, scope: Scope.ASSIGNED },
    { permission: Permission.TASK_EXPORT, scope: Scope.ASSIGNED },
    { permission: Permission.NOTE_READ, scope: Scope.ASSIGNED },
    { permission: Permission.NOTE_WRITE, scope: Scope.ASSIGNED },
    { permission: Permission.REPORT_READ, scope: Scope.ASSIGNED },
  ],
  [RoleCode.RECEPTION]: [
    { permission: Permission.APPOINTMENT_READ, scope: Scope.ORG },
    { permission: Permission.VISIT_READ, scope: Scope.ORG },
    { permission: Permission.VISIT_CHECKIN, scope: Scope.ORG },
    { permission: Permission.VISIT_CHECKOUT, scope: Scope.ORG },
    { permission: Permission.VISIT_DENY, scope: Scope.ORG },
  ],
  [RoleCode.SECURITY]: [
    { permission: Permission.APPOINTMENT_READ, scope: Scope.ORG },
    { permission: Permission.VISIT_READ, scope: Scope.ORG },
    { permission: Permission.VISIT_CHECKIN, scope: Scope.ORG },
    { permission: Permission.VISIT_CHECKOUT, scope: Scope.ORG },
    { permission: Permission.VISIT_DENY, scope: Scope.ORG },
  ],
  [RoleCode.EMPLOYEE]: [
    { permission: Permission.APPOINTMENT_CREATE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_READ, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_RESCHEDULE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_CANCEL, scope: Scope.OWN },
  ],
  [RoleCode.GUEST]: [
    { permission: Permission.APPOINTMENT_CREATE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_READ, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_RESCHEDULE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_CANCEL, scope: Scope.OWN },
  ],
  [RoleCode.AUDITOR]: [
    { permission: Permission.APPOINTMENT_READ, scope: Scope.ORG },
    { permission: Permission.REPORT_READ, scope: Scope.ORG },
    { permission: Permission.AUDIT_READ, scope: Scope.ORG },
  ],
  [RoleCode.STAFF]: [
    { permission: Permission.APPOINTMENT_CREATE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_READ, scope: Scope.ASSIGNED },
    { permission: Permission.APPOINTMENT_RESCHEDULE, scope: Scope.OWN },
    { permission: Permission.APPOINTMENT_CANCEL, scope: Scope.OWN },
    { permission: Permission.CALENDAR_READ, scope: Scope.ASSIGNED },
    { permission: Permission.VISIT_READ, scope: Scope.ASSIGNED },
    { permission: Permission.VISIT_CHECKIN, scope: Scope.ASSIGNED },
    { permission: Permission.VISIT_CHECKOUT, scope: Scope.ASSIGNED },
  ],
};
