import { RoleCode, Priority, AppointmentStatus, MeetingMode, TaskStatus, TaskCategory, VisitStatus, type AuthUser } from '@oams/shared';

export interface DemoUser extends AuthUser {
  roleTitle: string;
  avatarIcon: string;
}

export const DEMO_PERSONAS: Record<string, DemoUser> = {
  kvk: {
    id: 'usr-admin-1',
    email: 'kvk@stmarysgroup.com',
    fullName: 'Mr. KVK',
    roleTitle: 'Chairman & Official',
    orgId: 'org-apex-main',
    roles: [RoleCode.FACULTY],
    officialId: 'off-1',
    assignedOfficialIds: ['off-1'],
    avatarIcon: 'KVK',
    status: 'ACTIVE',
    authProvider: 'LOCAL',
    timezone: 'Asia/Kolkata',
    theme: 'SYSTEM',
  },
  harsha: {
    id: 'usr-ceo-1',
    email: 'harsha@stmarysgroup.com',
    fullName: 'Mr. Harsha Rao',
    roleTitle: 'Chief Executive Officer',
    orgId: 'org-apex-main',
    roles: [RoleCode.FACULTY],
    officialId: 'off-2',
    assignedOfficialIds: ['off-2'],
    avatarIcon: 'HR',
    status: 'ACTIVE',
    authProvider: 'LOCAL',
    timezone: 'Asia/Kolkata',
    theme: 'SYSTEM',
  },
  vc: {
    id: 'usr-vc-1',
    email: 'vc@stmarysgroup.com',
    fullName: 'VC',
    roleTitle: 'Vice Chancellor',
    orgId: 'org-apex-main',
    roles: [RoleCode.FACULTY],
    officialId: 'off-3',
    assignedOfficialIds: ['off-3'],
    avatarIcon: 'VC',
    status: 'ACTIVE',
    authProvider: 'LOCAL',
    timezone: 'Asia/Kolkata',
    theme: 'SYSTEM',
  },
  bharathi: {
    id: 'usr-bharathi-1',
    email: 'bharathi@stmarysgroup.com',
    fullName: 'Ms. Bharathi',
    roleTitle: 'President',
    orgId: 'org-apex-main',
    roles: [RoleCode.FACULTY],
    officialId: 'off-4',
    assignedOfficialIds: ['off-4'],
    avatarIcon: 'MB',
    status: 'ACTIVE',
    authProvider: 'LOCAL',
    timezone: 'Asia/Kolkata',
    theme: 'SYSTEM',
  },
  indhu: {
    id: 'usr-indhu-1',
    email: 'indhu@stmarysgroup.com',
    fullName: 'Ms. Indhu',
    roleTitle: 'Joint Secretary & Staff Officer',
    orgId: 'org-apex-main',
    roles: [RoleCode.STAFF],
    officialId: 'off-5',
    assignedOfficialIds: ['off-5'],
    avatarIcon: 'MI',
    status: 'ACTIVE',
    authProvider: 'LOCAL',
    timezone: 'Asia/Kolkata',
    theme: 'SYSTEM',
  },
  janardhan: {
    id: 'usr-janardhan-1',
    email: 'janardhan@stmarysgroup.com',
    fullName: 'Mr. Janardhan',
    roleTitle: 'Vice Principal / Staff Admin',
    orgId: 'org-apex-main',
    roles: [RoleCode.STAFF],
    officialId: 'off-6',
    assignedOfficialIds: ['off-6'],
    avatarIcon: 'MJ',
    status: 'ACTIVE',
    authProvider: 'LOCAL',
    timezone: 'Asia/Kolkata',
    theme: 'SYSTEM',
  },
  admin: {
    id: 'usr-admin-super',
    email: 'admin@stmarysgroup.com',
    fullName: 'System Administrator',
    roleTitle: 'Administrator',
    orgId: 'org-apex-main',
    roles: [RoleCode.ADMIN],
    officialId: null,
    assignedOfficialIds: ['off-1', 'off-2', 'off-3', 'off-4', 'off-5', 'off-6'],
    avatarIcon: 'AD',
    status: 'ACTIVE',
    authProvider: 'LOCAL',
    timezone: 'Asia/Kolkata',
    theme: 'SYSTEM',
  },
};

export const INITIAL_OFFICIALS = [
  {
    id: 'off-1',
    title: 'Mr.',
    fullName: 'Mr. KVK',
    full_name: 'Mr. KVK',
    userFullName: 'Mr. KVK',
    departmentName: 'Chamber of Mr. KVK',
    department_name: 'Chamber of Mr. KVK',
    designation: 'Official',
    defaultDurationMin: 30,
    isActive: true,
    is_active: true,
    userId: 'usr-admin-1',
  },
  {
    id: 'off-2',
    title: 'Mr.',
    fullName: 'Mr. Harsha Rao',
    full_name: 'Mr. Harsha Rao',
    userFullName: 'Mr. Harsha Rao',
    departmentName: 'Office of the Chief Executive Officer',
    department_name: 'Office of the Chief Executive Officer',
    designation: 'CEO',
    defaultDurationMin: 30,
    isActive: true,
    is_active: true,
    userId: 'usr-ceo-1',
  },
  {
    id: 'off-3',
    title: '',
    fullName: 'VC',
    full_name: 'VC',
    userFullName: 'VC',
    departmentName: 'Office of the Vice Chancellor',
    department_name: 'Office of the Vice Chancellor',
    designation: 'Vice Chancellor',
    defaultDurationMin: 45,
    isActive: true,
    is_active: true,
    userId: 'usr-vc-1',
  },
  {
    id: 'off-4',
    title: 'Ms.',
    fullName: 'Ms. Bharathi',
    full_name: 'Ms. Bharathi',
    userFullName: 'Ms. Bharathi',
    departmentName: 'Office of the President',
    department_name: 'Office of the President',
    designation: 'President',
    defaultDurationMin: 30,
    isActive: true,
    is_active: true,
    userId: 'usr-bharathi-1',
  },
  {
    id: 'off-5',
    title: 'Ms.',
    fullName: 'Ms. Indhu',
    full_name: 'Ms. Indhu',
    userFullName: 'Ms. Indhu',
    departmentName: 'Secretariat & Directorate',
    department_name: 'Secretariat & Directorate',
    designation: 'Joint Secretary',
    defaultDurationMin: 30,
    isActive: true,
    is_active: true,
    userId: 'usr-indhu-1',
  },
  {
    id: 'off-6',
    title: 'Mr.',
    fullName: 'Mr. Janardhan',
    full_name: 'Mr. Janardhan',
    userFullName: 'Mr. Janardhan',
    departmentName: 'Administration & Academic Affairs',
    department_name: 'Administration & Academic Affairs',
    designation: 'Vice Principal / Admin',
    defaultDurationMin: 30,
    isActive: true,
    is_active: true,
    userId: 'usr-janardhan-1',
  },
];

export const INITIAL_ROOMS = [
  {
    id: 'room-1',
    name: 'Chamber 101 (Executive Suite)',
    building: 'Main Secretariat',
    floor: '1st Floor',
    capacity: 10,
    isActive: true,
  },
  {
    id: 'room-2',
    name: 'Conference Room Alpha',
    building: 'Main Secretariat',
    floor: '2nd Floor',
    capacity: 35,
    isActive: true,
  },
  {
    id: 'room-3',
    name: 'Committee Room 4',
    building: 'Annex Building',
    floor: 'Ground Floor',
    capacity: 18,
    isActive: true,
  },
];

export const INITIAL_APPOINTMENTS = [
  // --- off-6: Mr. Janardhan (Vice Principal / Admin) ---
  {
    id: 'apt-601',
    referenceNo: 'OAMS-2026-00601',
    subject: 'Campus Security & Infrastructure Coordination',
    description: 'Review of visitor check-in counters, entry security protocols, and fire safety drill arrangements.',
    priority: Priority.HIGH,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-6',
    officialName: 'Mr. Janardhan',
    officialTitle: 'Vice Principal / Admin',
    requesterName: 'Mr. S. K. Nambiar',
    requesterEmail: 'estate@smru.edu.in',
    requesterPhone: '+91 98450 11223',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: new Date().toISOString().split('T')[0] + 'T10:00:00.000Z',
    scheduledEndTime: new Date().toISOString().split('T')[0] + 'T11:00:00.000Z',
    durationMin: 60,
    location: 'Admin Wing Conference',
    roomId: 'room-3',
    slaDueAt: '2026-09-29T10:00:00.000Z',
    attendees: [
      { name: 'Mr. S. K. Nambiar', organization: 'Campus Protocol & Estate', email: 'estate@smru.edu.in', isExternal: false },
    ],
  },
  {
    id: 'apt-602',
    referenceNo: 'OAMS-2026-00602',
    subject: 'Hostel Committee & Student Welfare Consultation',
    description: 'Review of hostel residential facilities, mess committee feedback, and student welfare provisions.',
    priority: Priority.MEDIUM,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-6',
    officialName: 'Mr. Janardhan',
    officialTitle: 'Vice Principal / Admin',
    requesterName: 'Dr. Sunita Sharma',
    requesterEmail: 'sunita.warden@smru.edu.in',
    requesterPhone: '+91 94411 22334',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-09-29T11:00:00.000Z',
    scheduledEndTime: '2026-09-29T12:00:00.000Z',
    durationMin: 60,
    location: 'Chamber 101 (Executive Suite)',
    roomId: 'room-1',
    slaDueAt: '2026-09-30T11:00:00.000Z',
    attendees: [
      { name: 'Dr. Sunita Sharma', organization: 'Hostel Administration', email: 'sunita.warden@smru.edu.in', isExternal: false },
    ],
  },
  {
    id: 'apt-603',
    referenceNo: 'OAMS-2026-00603',
    subject: 'Transport & Bus Fleet Safety Inspection',
    description: 'Quarterly roadworthiness audit, GPS tracking integration, and driver route scheduling.',
    priority: Priority.MEDIUM,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-6',
    officialName: 'Mr. Janardhan',
    officialTitle: 'Vice Principal / Admin',
    requesterName: 'K. Narayana Rao',
    requesterEmail: 'transport@smru.edu.in',
    requesterPhone: '+91 98855 44332',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-09-30T10:30:00.000Z',
    scheduledEndTime: '2026-09-30T11:30:00.000Z',
    durationMin: 60,
    location: 'Admin Wing Conference',
    roomId: 'room-3',
    slaDueAt: '2026-10-01T10:30:00.000Z',
    attendees: [
      { name: 'K. Narayana Rao', organization: 'Transport Operations', email: 'transport@smru.edu.in', isExternal: false },
    ],
  },
  {
    id: 'apt-604',
    referenceNo: 'OAMS-2026-00604',
    subject: 'Parent Council Representation — Academic Calendar',
    description: 'Representation by Parent-Teacher Association delegates concerning semester exam timing and student transit.',
    priority: Priority.HIGH,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-6',
    officialName: 'Mr. Janardhan',
    officialTitle: 'Vice Principal / Admin',
    requesterName: 'M. Venkatram',
    requesterEmail: 'venkatram.pta@smru.edu.in',
    requesterPhone: '+91 97000 88991',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-10-01T10:00:00.000Z',
    scheduledEndTime: '2026-10-01T11:00:00.000Z',
    durationMin: 60,
    location: 'Chamber 101 (Executive Suite)',
    roomId: 'room-1',
    slaDueAt: '2026-10-02T10:00:00.000Z',
    attendees: [
      { name: 'M. Venkatram', organization: 'Parent Council', email: 'venkatram.pta@smru.edu.in', isExternal: true },
    ],
  },
  {
    id: 'apt-605',
    referenceNo: 'OAMS-2026-00605',
    subject: 'Examination Cell Audit & Question Paper Security',
    description: 'Confidential security briefing and strong room surveillance review for university mid-term examinations.',
    priority: Priority.URGENT,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-6',
    officialName: 'Mr. Janardhan',
    officialTitle: 'Vice Principal / Admin',
    requesterName: 'Prof. S. R. Murthy',
    requesterEmail: 'coe@smru.edu.in',
    requesterPhone: '+91 94900 12345',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-10-01T14:30:00.000Z',
    scheduledEndTime: '2026-10-01T15:30:00.000Z',
    durationMin: 60,
    location: 'Conference Room Alpha',
    roomId: 'room-2',
    slaDueAt: '2026-10-02T14:30:00.000Z',
    attendees: [
      { name: 'Prof. S. R. Murthy', organization: 'Examination Cell', email: 'coe@smru.edu.in', isExternal: false },
    ],
  },
  {
    id: 'apt-606',
    referenceNo: 'OAMS-2026-00606',
    subject: 'Laboratory Equipment & Safety Protocol Review',
    description: 'Biochemistry and nano-materials research laboratory safety and statutory compliance verification.',
    priority: Priority.MEDIUM,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-6',
    officialName: 'Mr. Janardhan',
    officialTitle: 'Vice Principal / Admin',
    requesterName: 'Dr. K. Anuradha',
    requesterEmail: 'anuradha.labs@smru.edu.in',
    requesterPhone: '+91 98488 77665',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-10-02T11:00:00.000Z',
    scheduledEndTime: '2026-10-02T12:00:00.000Z',
    durationMin: 60,
    location: 'Admin Wing Conference',
    roomId: 'room-3',
    slaDueAt: '2026-10-03T11:00:00.000Z',
    attendees: [
      { name: 'Dr. K. Anuradha', organization: 'Department of Chemistry', email: 'anuradha.labs@smru.edu.in', isExternal: false },
    ],
  },

  // --- off-1: Mr. KVK (Chairman / Founder) ---
  {
    id: 'apt-101',
    referenceNo: 'OAMS-2026-00412',
    subject: 'High-Level Review of Campus Extension Corridor 3',
    description: 'Quarterly milestone review with contractors and institutional development delegates.',
    priority: Priority.HIGH,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-1',
    officialName: 'Mr. KVK',
    officialTitle: 'Chairman',
    requesterName: 'Sanjay Aggarwal',
    requesterEmail: 'sanjay.aggarwal@metrorail.gov.in',
    requesterPhone: '+91 98110 23456',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-10-01T10:30:00.000Z',
    scheduledEndTime: '2026-10-01T11:15:00.000Z',
    durationMin: 45,
    location: 'Chamber 101 (Executive Suite)',
    roomId: 'room-1',
    slaDueAt: '2026-10-02T18:00:00.000Z',
    attendees: [
      { name: 'Sanjay Aggarwal', organization: 'Metro Rail Corp', email: 'sanjay@metro.in', isExternal: true },
      { name: 'Meenakshi Sundaram', organization: 'Urban Planning', email: 'm.sundaram@apex.gov.in', isExternal: false },
    ],
  },
  {
    id: 'apt-105',
    referenceNo: 'OAMS-2026-00171',
    subject: 'ABC Corp — Industry Robotics MoU Signing',
    description: 'Strategic alliance discussion and signing of provisional MoU for student robotics center and campus recruitment.',
    priority: Priority.HIGH,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-1',
    officialName: 'Mr. KVK',
    officialTitle: 'Chairman',
    requesterName: 'Vikram Malhotra',
    requesterEmail: 'vikram@abccorp.in',
    requesterPhone: '+91 99000 11223',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-09-28T11:00:00.000Z',
    scheduledEndTime: '2026-09-28T12:00:00.000Z',
    durationMin: 60,
    location: 'Chamber 101 (Executive Suite)',
    roomId: 'room-1',
    slaDueAt: '2026-09-29T11:00:00.000Z',
    attendees: [
      { name: 'Vikram Malhotra', organization: 'ABC Corp', email: 'vikram@abccorp.in', isExternal: true },
    ],
  },
  {
    id: 'apt-106',
    referenceNo: 'OAMS-2026-00182',
    subject: 'State Higher Education Accreditation Council Liaison',
    description: 'High-level delegation meeting with State Education Secretary regarding NAAC criterion data verification.',
    priority: Priority.HIGH,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-1',
    officialName: 'Mr. KVK',
    officialTitle: 'Chairman',
    requesterName: 'Dr. Ramesh Chandra, IAS',
    requesterEmail: 'secy.he@state.gov.in',
    requesterPhone: '+91 94111 00998',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-10-02T10:00:00.000Z',
    scheduledEndTime: '2026-10-02T11:00:00.000Z',
    durationMin: 60,
    location: 'Chamber 101 (Executive Suite)',
    roomId: 'room-1',
    slaDueAt: '2026-10-03T10:00:00.000Z',
    attendees: [
      { name: 'Dr. Ramesh Chandra, IAS', organization: 'Higher Education Department', email: 'secy.he@state.gov.in', isExternal: true },
    ],
  },

  // --- off-2: Mr. Harsha Rao (CEO) ---
  {
    id: 'apt-102',
    referenceNo: 'OAMS-2026-00415',
    subject: 'Strategic Executive Briefing on AI & Innovation Center',
    description: 'Presentation on institutional guidelines and state-of-the-art laboratory expansion.',
    priority: Priority.URGENT,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-2',
    officialName: 'Mr. Harsha Rao',
    officialTitle: 'CEO',
    requesterName: 'Dr. Rajiv Sen',
    requesterEmail: 'rajiv@cloudsecure.io',
    requesterPhone: '+91 97200 44551',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-10-01T11:45:00.000Z',
    scheduledEndTime: '2026-10-01T12:30:00.000Z',
    durationMin: 45,
    location: 'Conference Room Alpha',
    roomId: 'room-2',
    slaDueAt: '2026-10-02T15:00:00.000Z',
    attendees: [
      { name: 'Dr. Rajiv Sen', organization: 'CloudSecure', email: 'rajiv@cloudsecure.io', isExternal: true },
    ],
  },
  {
    id: 'apt-202',
    referenceNo: 'OAMS-2026-00210',
    subject: 'Technical Operations Guild Review',
    description: 'Review of campus network backbone, server room redundancy, and cybersecurity posture.',
    priority: Priority.MEDIUM,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-2',
    officialName: 'Mr. Harsha Rao',
    officialTitle: 'CEO',
    requesterName: 'Operations Guild',
    requesterEmail: 'techops@smru.edu.in',
    requesterPhone: '+91 98111 22334',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-09-28T14:00:00.000Z',
    scheduledEndTime: '2026-09-28T15:00:00.000Z',
    durationMin: 60,
    location: 'Conference Room Alpha',
    roomId: 'room-2',
    slaDueAt: '2026-09-29T14:00:00.000Z',
    attendees: [
      { name: 'Devendra Patel', organization: 'Tech Operations', email: 'devendra@smru.edu.in', isExternal: false },
    ],
  },
  {
    id: 'apt-203',
    referenceNo: 'OAMS-2026-00176',
    subject: 'Vendor Contract Review — Microsoft Cloud Services',
    description: 'Annual license renewal and enterprise campus agreement review.',
    priority: Priority.MEDIUM,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-2',
    officialName: 'Mr. Harsha Rao',
    officialTitle: 'CEO',
    requesterName: 'Rajesh Sethi',
    requesterEmail: 'rajesh@mscloudpartner.com',
    requesterPhone: '+91 99222 33445',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-09-29T11:00:00.000Z',
    scheduledEndTime: '2026-09-29T12:00:00.000Z',
    durationMin: 60,
    location: 'Conference Room Alpha',
    roomId: 'room-2',
    slaDueAt: '2026-09-30T11:00:00.000Z',
    attendees: [
      { name: 'Rajesh Sethi', organization: 'MS Cloud Partner', email: 'rajesh@mscloudpartner.com', isExternal: true },
    ],
  },

  // --- off-3: VC (Vice Chancellor) ---
  {
    id: 'apt-103',
    referenceNo: 'OAMS-2026-00418',
    subject: 'Academic & Curriculum Modernization Review',
    description: 'Representation by Academic Council and department chairs regarding new degree specializations.',
    priority: Priority.MEDIUM,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-3',
    officialName: 'VC',
    officialTitle: 'Vice Chancellor',
    requesterName: 'Harish Varma',
    requesterEmail: 'harish.rwa@community.org',
    requesterPhone: '+91 99887 11223',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-10-01T10:00:00.000Z',
    scheduledEndTime: '2026-10-01T11:00:00.000Z',
    durationMin: 60,
    location: 'Chamber 101',
    roomId: 'room-1',
    slaDueAt: '2026-10-02T12:00:00.000Z',
    attendees: [
      { name: 'Harish Varma', organization: 'Central Academic Council', email: 'harish@rwa.org', isExternal: true },
    ],
  },
  {
    id: 'apt-301',
    referenceNo: 'OAMS-2026-00184',
    subject: 'Joint Research & Smart Campus Grant Review',
    description: 'Finalization of Phase 2 laboratory research grant with national science council.',
    priority: Priority.HIGH,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-3',
    officialName: 'VC',
    officialTitle: 'Vice Chancellor',
    requesterName: 'Priya Nambiar',
    requesterEmail: 'priya.nambiar@dst.gov.in',
    requesterPhone: '+91 98455 66778',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-09-30T11:00:00.000Z',
    scheduledEndTime: '2026-09-30T12:00:00.000Z',
    durationMin: 60,
    location: 'Chamber 101',
    roomId: 'room-1',
    slaDueAt: '2026-10-01T11:00:00.000Z',
    attendees: [
      { name: 'Priya Nambiar', organization: 'Department of Science', email: 'priya.nambiar@dst.gov.in', isExternal: true },
    ],
  },

  // --- off-4: Ms. Bharathi (President) ---
  {
    id: 'apt-104',
    referenceNo: 'OAMS-2026-00398',
    subject: 'Annual Strategic Institution Procurement Briefing',
    description: 'Briefing completed and minutes signed by management board for major equipment purchases.',
    priority: Priority.LOW,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-4',
    officialName: 'Ms. Bharathi',
    officialTitle: 'President',
    requesterName: 'Nandini Swaminathan',
    requesterEmail: 'nandini@digitalgov.org',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-09-29T10:00:00.000Z',
    scheduledEndTime: '2026-09-29T11:00:00.000Z',
    durationMin: 60,
    location: 'Office of the President',
    roomId: 'room-1',
    slaDueAt: '2026-09-30T10:00:00.000Z',
    attendees: [
      { name: 'Nandini Swaminathan', organization: 'State Procurement Directorate', email: 'nandini@digitalgov.org', isExternal: true },
    ],
  },
  {
    id: 'apt-402',
    referenceNo: 'OAMS-2026-00422',
    subject: 'Institutional Endowment & Alumni Fund Committee',
    description: 'Review of alumni donation allocations and merit scholarships for the incoming semester.',
    priority: Priority.HIGH,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-4',
    officialName: 'Ms. Bharathi',
    officialTitle: 'President',
    requesterName: 'Alumni Trust Executive',
    requesterEmail: 'alumni@smru.edu.in',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-10-01T14:00:00.000Z',
    scheduledEndTime: '2026-10-01T15:00:00.000Z',
    durationMin: 60,
    location: 'Office of the President',
    roomId: 'room-1',
    slaDueAt: '2026-10-02T14:00:00.000Z',
    attendees: [
      { name: 'Alumni Trust', organization: 'SMRU Alumni Foundation', email: 'alumni@smru.edu.in', isExternal: true },
    ],
  },

  // --- off-5: Ms. Indhu (Joint Secretary) ---
  {
    id: 'apt-501',
    referenceNo: 'OAMS-2026-00401',
    subject: 'Secretariat Workflow & File Triage',
    description: 'Review of incoming high-priority institutional correspondence and government notices.',
    priority: Priority.MEDIUM,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-5',
    officialName: 'Ms. Indhu',
    officialTitle: 'Joint Secretary',
    requesterName: 'Secretariat Directorate',
    requesterEmail: 'secretariat@smru.edu.in',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-09-28T09:30:00.000Z',
    scheduledEndTime: '2026-09-28T10:30:00.000Z',
    durationMin: 60,
    location: 'Conference Room Alpha',
    roomId: 'room-2',
    slaDueAt: '2026-09-29T09:30:00.000Z',
    attendees: [
      { name: 'Secretariat Officer', organization: 'Secretariat', email: 'secretariat@smru.edu.in', isExternal: false },
    ],
  },
  {
    id: 'apt-502',
    referenceNo: 'OAMS-2026-00430',
    subject: 'Recruitment Drives & Placement Coordination',
    description: 'Coordination meeting with Tier-1 recruiters and placement team.',
    priority: Priority.HIGH,
    status: AppointmentStatus.CONFIRMED,
    officialId: 'off-5',
    officialName: 'Ms. Indhu',
    officialTitle: 'Joint Secretary',
    requesterName: 'Placement Director',
    requesterEmail: 'placements@smru.edu.in',
    meetingMode: MeetingMode.IN_PERSON,
    scheduledStartTime: '2026-10-01T11:00:00.000Z',
    scheduledEndTime: '2026-10-01T12:00:00.000Z',
    durationMin: 60,
    location: 'Conference Room Alpha',
    roomId: 'room-2',
    slaDueAt: '2026-10-02T11:00:00.000Z',
    attendees: [
      { name: 'Placement Director', organization: 'Career Development Cell', email: 'placements@smru.edu.in', isExternal: false },
    ],
  },
];

export const INITIAL_TASKS = [
  // Mr. KVK (Chairman / Founder) - off-1 / usr-admin-1
  {
    id: 'tsk-1',
    title: 'Review and sign academic accreditation compliance note',
    description: 'Urgent compliance documentation required prior to committee meeting on Friday.',
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    category: TaskCategory.REVIEW,
    officialId: 'off-1',
    officialName: 'Mr. KVK',
    assignedToId: 'usr-admin-1',
    assignedToName: 'Mr. KVK',
    createdById: 'usr-admin-1',
    createdByName: 'Mr. KVK',
    dueDate: new Date(Date.now() + 14 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 14 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Accreditation', 'Environment', 'Priority'],
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-kvk-2',
    title: 'Finalize Annual Board of Trustees strategy memorandum',
    description: 'Executive briefing on campus expansion and capital budget for next fiscal cycle.',
    status: TaskStatus.TODO,
    priority: Priority.URGENT,
    category: TaskCategory.DOCUMENT,
    officialId: 'off-1',
    officialName: 'Mr. KVK',
    assignedToId: 'usr-admin-1',
    assignedToName: 'Mr. KVK',
    createdById: 'usr-admin-1',
    createdByName: 'Mr. KVK',
    dueDate: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Board', 'Strategy', 'Executive'],
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-kvk-3',
    title: 'Approve Phase 2 Smart Campus budget allocation',
    description: 'Financial committee approval sheet for infrastructure digital transformation.',
    status: TaskStatus.TODO,
    priority: Priority.MEDIUM,
    category: TaskCategory.APPROVAL,
    officialId: 'off-1',
    officialName: 'Mr. KVK',
    assignedToId: 'usr-admin-1',
    assignedToName: 'Mr. KVK',
    createdById: 'usr-admin-1',
    createdByName: 'Mr. KVK',
    dueDate: new Date(Date.now() + 48 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 48 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Finance', 'Campus', 'Infrastructure'],
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-kvk-4',
    title: 'Executive sign-off on new chancellor appointment committee',
    description: 'Nomination files verified and signed off for council records.',
    status: TaskStatus.DONE,
    priority: Priority.LOW,
    category: TaskCategory.APPROVAL,
    officialId: 'off-1',
    officialName: 'Mr. KVK',
    assignedToId: 'usr-admin-1',
    assignedToName: 'Mr. KVK',
    createdById: 'usr-admin-1',
    createdByName: 'Mr. KVK',
    dueDate: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Governance', 'Appointments'],
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },

  // Mr. Harsha Rao (CEO) - off-2 / usr-ceo-1
  {
    id: 'tsk-2',
    title: 'Prepare executive dossier for bilateral university delegation',
    description: 'Include 1-pager summary, verified visitor list, and protocol checklist.',
    status: TaskStatus.TODO,
    priority: Priority.URGENT,
    category: TaskCategory.DOCUMENT,
    officialId: 'off-2',
    officialName: 'Mr. Harsha Rao',
    assignedToId: 'usr-ceo-1',
    assignedToName: 'Mr. Harsha Rao',
    createdById: 'usr-ceo-1',
    createdByName: 'Mr. Harsha Rao',
    dueDate: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['University', 'VIP', 'Dossier'],
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-harsha-2',
    title: 'Conduct Q3 operational spend audit with finance secretariat',
    description: 'Comprehensive review of operational expenditure vs approved budget caps.',
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    category: TaskCategory.REVIEW,
    officialId: 'off-2',
    officialName: 'Mr. Harsha Rao',
    assignedToId: 'usr-ceo-1',
    assignedToName: 'Mr. Harsha Rao',
    createdById: 'usr-ceo-1',
    createdByName: 'Mr. Harsha Rao',
    dueDate: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Audit', 'Finance', 'Q3'],
    createdAt: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-harsha-3',
    title: 'Review international partnership MoU draft with Singapore Tech Institute',
    description: 'Legal vetting of student exchange quota and dual certification clauses.',
    status: TaskStatus.TODO,
    priority: Priority.MEDIUM,
    category: TaskCategory.REVIEW,
    officialId: 'off-2',
    officialName: 'Mr. Harsha Rao',
    assignedToId: 'usr-ceo-1',
    assignedToName: 'Mr. Harsha Rao',
    createdById: 'usr-ceo-1',
    createdByName: 'Mr. Harsha Rao',
    dueDate: new Date(Date.now() + 36 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 36 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['MoU', 'International', 'Partnership'],
    createdAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-harsha-4',
    title: 'Weekly strategic governance and operational alignment meeting with Chairman Mr. KVK',
    description: 'Review agenda notes and action items completed from previous review session.',
    status: TaskStatus.DONE,
    priority: Priority.LOW,
    category: TaskCategory.OTHER,
    officialId: 'off-2',
    officialName: 'Mr. Harsha Rao',
    assignedToId: 'usr-ceo-1',
    assignedToName: 'Mr. Harsha Rao',
    createdById: 'usr-ceo-1',
    createdByName: 'Mr. Harsha Rao',
    dueDate: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Governance', 'Executive'],
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },

  // VC (Vice Chancellor) - off-3 / usr-vc-1
  {
    id: 'tsk-vc-1',
    title: 'Publish revised semester examination schedules and protocol',
    description: 'Ensure notification is circulated to all affiliated collegiate deans and portals.',
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    category: TaskCategory.DOCUMENT,
    officialId: 'off-3',
    officialName: 'VC',
    assignedToId: 'usr-vc-1',
    assignedToName: 'VC',
    createdById: 'usr-vc-1',
    createdByName: 'VC',
    dueDate: new Date(Date.now() + 12 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 12 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Exams', 'Academic', 'Notice'],
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-vc-2',
    title: 'Convene Academic Senate emergency session on syllabus revision',
    description: 'Prepare quorum register and presentation on industry-aligned curriculum changes.',
    status: TaskStatus.TODO,
    priority: Priority.URGENT,
    category: TaskCategory.MEETING,
    officialId: 'off-3',
    officialName: 'VC',
    assignedToId: 'usr-vc-1',
    assignedToName: 'VC',
    createdById: 'usr-vc-1',
    createdByName: 'VC',
    dueDate: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Senate', 'Curriculum', 'Urgent'],
    createdAt: new Date(Date.now() - 7 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-vc-3',
    title: 'Inspect doctoral research defense proceedings at Auditorium 2',
    description: 'Review research evaluation committee report and candidate public viva.',
    status: TaskStatus.TODO,
    priority: Priority.MEDIUM,
    category: TaskCategory.REVIEW,
    officialId: 'off-3',
    officialName: 'VC',
    assignedToId: 'usr-vc-1',
    assignedToName: 'VC',
    createdById: 'usr-vc-1',
    createdByName: 'VC',
    dueDate: new Date(Date.now() + 30 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 30 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Research', 'PhD', 'Viva'],
    createdAt: new Date(Date.now() - 15 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-vc-4',
    title: 'Approve department head nominations for School of Computing',
    description: 'Appointment dossiers checked against UGC qualification criteria.',
    status: TaskStatus.DONE,
    priority: Priority.LOW,
    category: TaskCategory.APPROVAL,
    officialId: 'off-3',
    officialName: 'VC',
    assignedToId: 'usr-vc-1',
    assignedToName: 'VC',
    createdById: 'usr-vc-1',
    createdByName: 'VC',
    dueDate: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Faculty', 'Appointment'],
    createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
  },

  // Ms. Bharathi (President) - off-4 / usr-bharathi-1
  {
    id: 'tsk-4',
    title: 'Sign dispatch letters for governing council quarterly conference',
    description: 'Dispatches finalized and printed for review.',
    status: TaskStatus.DONE,
    priority: Priority.LOW,
    category: TaskCategory.APPROVAL,
    officialId: 'off-4',
    officialName: 'Ms. Bharathi',
    assignedToId: 'usr-bharathi-1',
    assignedToName: 'Ms. Bharathi',
    createdById: 'usr-bharathi-1',
    createdByName: 'Ms. Bharathi',
    dueDate: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Dispatch', 'Routine'],
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-bharathi-2',
    title: 'Audit institutional endowment fund distributions',
    description: 'Review quarterly disbursement statement from trust accounts.',
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    category: TaskCategory.REVIEW,
    officialId: 'off-4',
    officialName: 'Ms. Bharathi',
    assignedToId: 'usr-bharathi-1',
    assignedToName: 'Ms. Bharathi',
    createdById: 'usr-bharathi-1',
    createdByName: 'Ms. Bharathi',
    dueDate: new Date(Date.now() + 16 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 16 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Endowment', 'Trust', 'Finance'],
    createdAt: new Date(Date.now() - 9 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-bharathi-3',
    title: 'Review faculty welfare and grievance committee submissions',
    description: 'Examine confidential staff representation on healthcare and family welfare policies.',
    status: TaskStatus.TODO,
    priority: Priority.MEDIUM,
    category: TaskCategory.DOCUMENT,
    officialId: 'off-4',
    officialName: 'Ms. Bharathi',
    assignedToId: 'usr-bharathi-1',
    assignedToName: 'Ms. Bharathi',
    createdById: 'usr-bharathi-1',
    createdByName: 'Ms. Bharathi',
    dueDate: new Date(Date.now() + 26 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 26 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Welfare', 'Faculty', 'Policy'],
    createdAt: new Date(Date.now() - 11 * 3600 * 1000).toISOString(),
  },

  // Ms. Indhu (Joint Secretary / PA) - off-5 / usr-indhu-1
  {
    id: 'tsk-indhu-1',
    title: 'Coordinate protocol itinerary for Metro Rail Chairman visit',
    description: 'Confirm VIP parking slot, security escort details, and boardroom refreshments.',
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.URGENT,
    category: TaskCategory.OTHER,
    officialId: 'off-5',
    officialName: 'Ms. Indhu',
    assignedToId: 'usr-indhu-1',
    assignedToName: 'Ms. Indhu',
    createdById: 'usr-indhu-1',
    createdByName: 'Ms. Indhu',
    dueDate: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Protocol', 'VIP', 'Reception'],
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-indhu-2',
    title: 'Collate security clearances and VIP vehicle passes for Main Gate',
    description: 'Liaise with Mr. Janardhan at security desk for gate pass issuance.',
    status: TaskStatus.TODO,
    priority: Priority.HIGH,
    category: TaskCategory.REVIEW,
    officialId: 'off-5',
    officialName: 'Ms. Indhu',
    assignedToId: 'usr-indhu-1',
    assignedToName: 'Ms. Indhu',
    createdById: 'usr-indhu-1',
    createdByName: 'Ms. Indhu',
    dueDate: new Date(Date.now() + 10 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 10 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Security', 'Passes', 'Coordination'],
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-indhu-3',
    title: 'Archive previous week verified meeting minutes and audio recordings',
    description: 'Upload signed PDFs to secure document repository per §18 compliance standards.',
    status: TaskStatus.DONE,
    priority: Priority.LOW,
    category: TaskCategory.DOCUMENT,
    officialId: 'off-5',
    officialName: 'Ms. Indhu',
    assignedToId: 'usr-indhu-1',
    assignedToName: 'Ms. Indhu',
    createdById: 'usr-indhu-1',
    createdByName: 'Ms. Indhu',
    dueDate: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Compliance', 'Archive'],
    createdAt: new Date(Date.now() - 28 * 3600 * 1000).toISOString(),
  },

  // Mr. Janardhan (Vice Principal / Admin / Reception) - off-6 / usr-janardhan-1
  {
    id: 'tsk-3',
    title: 'Inspect campus infrastructure and visitor pass terminal at Main Gate',
    description: 'Biometric pass terminal maintenance routine check.',
    status: TaskStatus.TODO,
    priority: Priority.MEDIUM,
    category: TaskCategory.OTHER,
    officialId: 'off-6',
    officialName: 'Mr. Janardhan',
    assignedToId: 'usr-janardhan-1',
    assignedToName: 'Mr. Janardhan',
    createdById: 'usr-janardhan-1',
    createdByName: 'Mr. Janardhan',
    dueDate: new Date(Date.now() + 28 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 28 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Security', 'Maintenance'],
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-janardhan-2',
    title: 'Audit visitor badge logs and vehicle registration database',
    description: 'Reconcile RFID badge issuances against checkout gate logs for the day.',
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    category: TaskCategory.REVIEW,
    officialId: 'off-6',
    officialName: 'Mr. Janardhan',
    assignedToId: 'usr-janardhan-1',
    assignedToName: 'Mr. Janardhan',
    createdById: 'usr-janardhan-1',
    createdByName: 'Mr. Janardhan',
    dueDate: new Date(Date.now() + 7 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 7 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Badges', 'Audit', 'Gate'],
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-janardhan-3',
    title: 'Review security perimeter patrol log and CCTV surveillance check',
    description: 'Ensure boundary sensors and CCTV feeds on North Perimeter are operational.',
    status: TaskStatus.TODO,
    priority: Priority.URGENT,
    category: TaskCategory.OTHER,
    officialId: 'off-6',
    officialName: 'Mr. Janardhan',
    assignedToId: 'usr-janardhan-1',
    assignedToName: 'Mr. Janardhan',
    createdById: 'usr-janardhan-1',
    createdByName: 'Mr. Janardhan',
    dueDate: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['CCTV', 'Perimeter', 'Safety'],
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tsk-janardhan-4',
    title: 'Dispatch monthly campus safety compliance certification',
    description: 'Fire extinguisher inspections and emergency exit checks confirmed complete.',
    status: TaskStatus.DONE,
    priority: Priority.LOW,
    category: TaskCategory.DOCUMENT,
    officialId: 'off-6',
    officialName: 'Mr. Janardhan',
    assignedToId: 'usr-janardhan-1',
    assignedToName: 'Mr. Janardhan',
    createdById: 'usr-janardhan-1',
    createdByName: 'Mr. Janardhan',
    dueDate: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    isPersonal: false,
    tags: ['Safety', 'Certification'],
    createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
  },
];

const makeVisitIsoTime = (hour: number, minute: number = 0) => {
  const d = new Date();
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};

export const INITIAL_VISITS = [
  // --- off-6: Mr. Janardhan - Mr. S. K. Nambiar (OAMS-2026-00601) ---
  {
    id: 'vis-601',
    orgId: 'org-apex-main',
    appointmentId: 'apt-601',
    referenceNo: 'OAMS-2026-00601',
    qrToken: '00601',
    visitorName: 'Mr. S. K. Nambiar',
    phone: '+91 98450 11223',
    email: 'estate@smru.edu.in',
    organization: 'Campus Protocol & Estate',
    idType: 'OFFICE_ID',
    idLast4: '1123',
    vehicleNo: 'TS 09 AB 1234',
    partySize: 1,
    status: VisitStatus.EXPECTED,
    badgeNo: null,
    badgeNumber: null,
    hostOfficialId: 'off-6',
    hostOfficialName: 'Mr. Janardhan',
    officialName: 'Mr. Janardhan',
    hostOfficialTitle: 'Vice Principal / Admin',
    scheduledStartTime: makeVisitIsoTime(10, 0),
    scheduledEndTime: makeVisitIsoTime(11, 0),
    scheduledAt: makeVisitIsoTime(10, 0),
    roomName: 'Admin Wing Conference',
    building: 'Administration Wing',
    floor: '1st Floor',
    subject: 'Campus Security & Infrastructure Coordination',
    purpose: 'Review of visitor check-in counters, entry security protocols, and fire safety drill arrangements.',
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  // --- Ms. Bharathi's Chamber Visitors ---
  {
    id: 'vis-bh-1',
    orgId: 'org-apex-main',
    appointmentId: 'apt-bh-1',
    referenceNo: 'OAMS-2026-00311',
    qrToken: '00311',
    visitorName: 'Dr. Ramesh Chandra, IAS',
    phone: '+91 98230 11984',
    email: 'r.chandra.ias@highered.gov.in',
    organization: 'Higher Education Accreditation Council',
    idType: 'OFFICE_ID',
    idLast4: '6641',
    vehicleNo: 'DL 01 CD 5521',
    partySize: 2,
    status: VisitStatus.EXPECTED,
    badgeNo: null,
    badgeNumber: null,
    hostOfficialId: 'off-4',
    hostOfficialName: 'Ms. Bharathi',
    officialName: 'Ms. Bharathi',
    hostOfficialTitle: 'President',
    scheduledStartTime: makeVisitIsoTime(11, 30),
    scheduledEndTime: makeVisitIsoTime(12, 15),
    scheduledAt: makeVisitIsoTime(11, 30),
    roomName: 'President Secretariat (Room 102)',
    building: 'Main Secretariat',
    floor: '1st Floor',
    subject: 'Autonomous Accreditation & Institutional Compliance Review',
    purpose: 'Presentation of formal national accreditation assessment report.',
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'vis-bh-2',
    orgId: 'org-apex-main',
    appointmentId: 'apt-bh-2',
    referenceNo: 'OAMS-2026-00325',
    qrToken: '00325',
    visitorName: 'Smt. Sunitha Rao',
    phone: '+91 97110 54321',
    email: 'sunitha.rao@nsrf.res.in',
    organization: 'National Science & Research Foundation',
    idType: 'AADHAAR',
    idLast4: '3310',
    vehicleNo: 'KA 05 MN 8820',
    partySize: 1,
    status: VisitStatus.EXPECTED,
    badgeNo: null,
    badgeNumber: null,
    hostOfficialId: 'off-4',
    hostOfficialName: 'Ms. Bharathi',
    officialName: 'Ms. Bharathi',
    hostOfficialTitle: 'President',
    scheduledStartTime: makeVisitIsoTime(14, 30),
    scheduledEndTime: makeVisitIsoTime(15, 15),
    scheduledAt: makeVisitIsoTime(14, 30),
    roomName: 'Executive Boardroom',
    building: 'Main Secretariat',
    floor: '1st Floor',
    subject: 'Women in STEM Research Grant Evaluation',
    purpose: 'Finalizing multi-year laboratory grants for research scholars.',
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'vis-bh-3',
    orgId: 'org-apex-main',
    appointmentId: 'apt-bh-3',
    referenceNo: 'OAMS-2026-00342',
    qrToken: '00342',
    visitorName: 'Vikramaditya Singhania',
    phone: '+91 98101 22334',
    email: 'v.singhania@ltinfra.com',
    organization: 'L&T Infrastructure Advisory',
    idType: 'OFFICE_ID',
    idLast4: '4819',
    vehicleNo: 'DL 08 CA 4421',
    partySize: 2,
    status: VisitStatus.ARRIVED,
    badgeNo: null,
    badgeNumber: null,
    arrivedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    hostOfficialId: 'off-4',
    hostOfficialName: 'Ms. Bharathi',
    officialName: 'Ms. Bharathi',
    hostOfficialTitle: 'President',
    scheduledStartTime: makeVisitIsoTime(11, 45),
    scheduledEndTime: makeVisitIsoTime(12, 30),
    scheduledAt: makeVisitIsoTime(11, 45),
    roomName: 'President Secretariat (Room 102)',
    building: 'Main Secretariat',
    floor: '1st Floor',
    subject: 'Campus Expansion Phase 2 Architectural Blueprint Review',
    purpose: 'On-site review of civil construction drawings and security permits.',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
  },
  {
    id: 'vis-bh-4',
    orgId: 'org-apex-main',
    appointmentId: 'apt-bh-4',
    referenceNo: 'OAMS-2026-00288',
    qrToken: '00288',
    visitorName: 'Dr. Meenakshi Sundaram',
    phone: '+91 94451 98765',
    email: 'm.sundaram@london.ac.uk',
    organization: 'Univ. of London Academic Delegation',
    idType: 'PASSPORT',
    idLast4: '9921',
    vehicleNo: null,
    partySize: 1,
    status: VisitStatus.CHECKED_IN,
    badgeNo: 'B-927',
    badgeNumber: 'B-927',
    arrivedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    checkedInAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
    waitingMinutes: 9,
    hostOfficialId: 'off-4',
    hostOfficialName: 'Ms. Bharathi',
    officialName: 'Ms. Bharathi',
    hostOfficialTitle: 'President',
    scheduledStartTime: makeVisitIsoTime(11, 0),
    scheduledEndTime: makeVisitIsoTime(11, 45),
    scheduledAt: makeVisitIsoTime(11, 0),
    roomName: 'President Secretariat (Room 102)',
    building: 'Main Secretariat',
    floor: '1st Floor',
    subject: 'Dual Degree MoU & Faculty Exchange Program',
    purpose: 'Signing of institutional partnership agreement.',
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
  },
  {
    id: 'vis-bh-5',
    orgId: 'org-apex-main',
    appointmentId: 'apt-bh-5',
    referenceNo: 'OAMS-2026-00244',
    qrToken: '00244',
    visitorName: 'Shri Arvind Swaminathan',
    phone: '+91 99002 11223',
    email: 'a.swaminathan@highered.gov.in',
    organization: 'Dept of Higher Education (Principal Secretary)',
    idType: 'GOVT_ID',
    idLast4: '1001',
    vehicleNo: 'TS 09 BG 0001',
    partySize: 1,
    status: VisitStatus.WITH_HOST,
    badgeNo: 'VIP-04',
    badgeNumber: 'VIP-04',
    arrivedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    checkedInAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    withHostAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    hostOfficialId: 'off-4',
    hostOfficialName: 'Ms. Bharathi',
    officialName: 'Ms. Bharathi',
    hostOfficialTitle: 'President',
    scheduledStartTime: makeVisitIsoTime(10, 30),
    scheduledEndTime: makeVisitIsoTime(11, 30),
    scheduledAt: makeVisitIsoTime(10, 30),
    roomName: 'President Executive Chamber',
    building: 'Main Secretariat',
    floor: '1st Floor',
    subject: 'State Higher Education Reforms & Institutional Endowment',
    purpose: 'Policy discussion on campus autonomy and scholarship funding.',
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
  },
  {
    id: 'vis-bh-6',
    orgId: 'org-apex-main',
    appointmentId: 'apt-105',
    referenceNo: 'OAMS-2026-00179',
    qrToken: '00179',
    visitorName: 'Prof. K. Satyanarayana',
    phone: '+91 94401 55667',
    email: 'satya.k@iitb.ac.in',
    organization: 'IIT Madras Collaboration Committee',
    idType: 'OFFICE_ID',
    idLast4: '7732',
    vehicleNo: null,
    partySize: 1,
    status: VisitStatus.CHECKED_OUT,
    badgeNo: 'B-118',
    badgeNumber: 'B-118',
    arrivedAt: new Date(Date.now() - 140 * 60 * 1000).toISOString(),
    checkedInAt: new Date(Date.now() - 125 * 60 * 1000).toISOString(),
    withHostAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    checkedOutAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    hostOfficialId: 'off-4',
    hostOfficialName: 'Ms. Bharathi',
    officialName: 'Ms. Bharathi',
    hostOfficialTitle: 'President',
    scheduledStartTime: makeVisitIsoTime(9, 30),
    scheduledEndTime: makeVisitIsoTime(10, 30),
    scheduledAt: makeVisitIsoTime(9, 30),
    roomName: 'Committee Room 4',
    building: 'Annex Building',
    floor: 'Ground Floor',
    subject: 'Academic Exchange & Faculty Development MoA',
    purpose: 'Review and sign exchange fellowship program guidelines.',
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },

  // --- Other Officials Institutional Visitors ---
  {
    id: 'vis-101',
    orgId: 'org-apex-main',
    appointmentId: 'apt-101',
    referenceNo: 'OAMS-2026-00412',
    qrToken: '00412',
    visitorName: 'Sanjay Aggarwal',
    phone: '+91 98110 23456',
    email: 'sanjay.aggarwal@metrorail.gov.in',
    organization: 'Metro Rail Corp',
    idType: 'AADHAAR',
    idLast4: '4819',
    vehicleNo: 'DL 01 AB 7788',
    partySize: 2,
    status: VisitStatus.EXPECTED,
    badgeNo: null,
    badgeNumber: null,
    hostOfficialId: 'off-1',
    hostOfficialName: 'Mr. KVK',
    officialName: 'Mr. KVK',
    hostOfficialTitle: 'Chairman',
    scheduledStartTime: makeVisitIsoTime(14, 0),
    scheduledEndTime: makeVisitIsoTime(14, 45),
    scheduledAt: makeVisitIsoTime(14, 0),
    roomName: 'Chamber 101 (Executive Suite)',
    building: 'Main Secretariat',
    floor: '1st Floor',
    subject: 'High-Level Review of Campus Extension Corridor 3',
    purpose: 'Quarterly milestone review with contractors and institutional development delegates.',
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
  {
    id: 'vis-kvk-arrived',
    orgId: 'org-apex-main',
    appointmentId: 'apt-101-b',
    referenceNo: 'OAMS-2026-00418',
    qrToken: '00418',
    visitorName: 'Mahesh Sharma',
    phone: '+91 98115 44321',
    email: 'm.sharma@ltenergy.com',
    organization: 'L&T Energy & Infrastructure',
    idType: 'OFFICE_ID',
    idLast4: '4920',
    vehicleNo: 'DL 03 CA 1024',
    partySize: 2,
    status: VisitStatus.ARRIVED,
    badgeNo: null,
    badgeNumber: null,
    arrivedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    hostOfficialId: 'off-1',
    hostOfficialName: 'Mr. KVK',
    officialName: 'Mr. KVK',
    hostOfficialTitle: 'Chairman',
    scheduledStartTime: makeVisitIsoTime(12, 0),
    scheduledEndTime: makeVisitIsoTime(12, 45),
    scheduledAt: makeVisitIsoTime(12, 0),
    roomName: 'Chamber 101 (Executive Suite)',
    building: 'Main Secretariat',
    floor: '1st Floor',
    subject: 'Green Hydrogen Micro-Grid Project Review',
    purpose: 'Presentation on campus micro-grid installation and renewable backup systems.',
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'vis-107',
    orgId: 'org-apex-main',
    appointmentId: 'apt-101',
    referenceNo: 'OAMS-2026-00412-A',
    qrToken: '00412-A',
    visitorName: 'Er. Alok Verma',
    phone: '+91 98450 12345',
    email: 'alok.verma@metrorail.gov.in',
    organization: 'Metro Rail Project Team',
    idType: 'OFFICE_ID',
    idLast4: '7721',
    vehicleNo: 'TS 07 HK 9090',
    partySize: 2,
    status: VisitStatus.CHECKED_IN,
    badgeNo: 'VIP-02',
    badgeNumber: 'VIP-02',
    arrivedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    checkedInAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    waitingMinutes: 12,
    hostOfficialId: 'off-1',
    hostOfficialName: 'Mr. KVK',
    officialName: 'Mr. KVK',
    hostOfficialTitle: 'Chairman & Founder',
    scheduledStartTime: makeVisitIsoTime(11, 45),
    scheduledEndTime: makeVisitIsoTime(12, 30),
    scheduledAt: makeVisitIsoTime(11, 45),
    roomName: 'Chamber 101 (Executive Suite)',
    building: 'Main Secretariat',
    floor: '1st Floor',
    subject: 'High-Level Review of Campus Extension Corridor 3',
    purpose: 'On-site technical presentation on civil infrastructure alignment.',
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    id: 'vis-kvk-withhost',
    orgId: 'org-apex-main',
    appointmentId: 'apt-101-c',
    referenceNo: 'OAMS-2026-00405',
    qrToken: '00405',
    visitorName: 'Col. Rajendra Singh',
    phone: '+91 99100 88765',
    email: 'r.singh@sicouncil.gov.in',
    organization: 'Strategic Infrastructure Council',
    idType: 'GOVT_ID',
    idLast4: '0017',
    vehicleNo: 'DL 01 AA 0007',
    partySize: 1,
    status: VisitStatus.WITH_HOST,
    badgeNo: 'VIP-01',
    badgeNumber: 'VIP-01',
    arrivedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    checkedInAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    withHostAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    hostOfficialId: 'off-1',
    hostOfficialName: 'Mr. KVK',
    officialName: 'Mr. KVK',
    hostOfficialTitle: 'Chairman & Founder',
    scheduledStartTime: makeVisitIsoTime(11, 30),
    scheduledEndTime: makeVisitIsoTime(12, 15),
    scheduledAt: makeVisitIsoTime(11, 30),
    roomName: 'Chamber 101 (Executive Suite)',
    building: 'Main Secretariat',
    floor: '1st Floor',
    subject: 'Campus Perimeter Security & High-Level Corridor Strategy',
    purpose: 'Confidential advisory meeting on institutional security protocols and infrastructure master plan.',
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'vis-kvk-checkedout',
    orgId: 'org-apex-main',
    appointmentId: 'apt-101-d',
    referenceNo: 'OAMS-2026-00388',
    qrToken: '00388',
    visitorName: 'Prof. Deepak Joshi',
    phone: '+91 94450 77123',
    email: 'd.joshi@iitb.ac.in',
    organization: 'IIT Bombay Advisory Directorate',
    idType: 'OFFICE_ID',
    idLast4: '8823',
    vehicleNo: 'MH 02 BG 3311',
    partySize: 1,
    status: VisitStatus.CHECKED_OUT,
    badgeNo: 'VIP-03',
    badgeNumber: 'VIP-03',
    arrivedAt: new Date(Date.now() - 130 * 60 * 1000).toISOString(),
    checkedInAt: new Date(Date.now() - 115 * 60 * 1000).toISOString(),
    withHostAt: new Date(Date.now() - 100 * 60 * 1000).toISOString(),
    checkedOutAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    hostOfficialId: 'off-1',
    hostOfficialName: 'Mr. KVK',
    officialName: 'Mr. KVK',
    hostOfficialTitle: 'Chairman & Founder',
    scheduledStartTime: makeVisitIsoTime(10, 0),
    scheduledEndTime: makeVisitIsoTime(11, 0),
    scheduledAt: makeVisitIsoTime(10, 0),
    roomName: 'Chamber 101 (Executive Suite)',
    building: 'Main Secretariat',
    floor: '1st Floor',
    subject: 'Joint Center of Excellence & AI Research Lab Launch',
    purpose: 'Signing and review of formal bilateral research fellowship agreement.',
    createdAt: new Date(Date.now() - 7 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'vis-102',
    orgId: 'org-apex-main',
    appointmentId: 'apt-102',
    referenceNo: 'OAMS-2026-00171',
    qrToken: '00171',
    visitorName: 'Dr. Vikram Sethi',
    phone: '+91 98765 43210',
    email: 'v.sethi@aiconsortium.edu',
    organization: 'National AI & Tech Consortium',
    idType: 'GOVT_ID',
    idLast4: '9021',
    vehicleNo: 'TS 09 EQ 4402',
    partySize: 1,
    status: VisitStatus.ARRIVED,
    badgeNo: null,
    badgeNumber: null,
    arrivedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    hostOfficialId: 'off-2',
    hostOfficialName: 'Mr. Harsha Rao',
    officialName: 'Mr. Harsha Rao',
    hostOfficialTitle: 'CEO',
    scheduledStartTime: makeVisitIsoTime(12, 30),
    scheduledEndTime: makeVisitIsoTime(13, 15),
    scheduledAt: makeVisitIsoTime(12, 30),
    roomName: 'Conference Room Alpha',
    building: 'Main Secretariat',
    floor: '2nd Floor',
    subject: 'Strategic Executive Briefing on AI & Innovation Center',
    purpose: 'Presentation on institutional guidelines and state-of-the-art laboratory expansion.',
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'vis-103',
    orgId: 'org-apex-main',
    appointmentId: 'apt-103',
    referenceNo: 'OAMS-2026-00182',
    qrToken: '00182',
    visitorName: 'Rajesh Gopinathan',
    phone: '+91 98230 44556',
    email: 'r.gopinathan@tcs.com',
    organization: 'Tata Consultancy Services',
    idType: 'OFFICE_ID',
    idLast4: '8812',
    vehicleNo: 'MH 12 CD 3311',
    partySize: 2,
    status: VisitStatus.CHECKED_IN,
    badgeNo: 'B-402',
    badgeNumber: 'B-402',
    arrivedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    checkedInAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    waitingMinutes: 15,
    hostOfficialId: 'off-2',
    hostOfficialName: 'Mr. Harsha Rao',
    officialName: 'Mr. Harsha Rao',
    hostOfficialTitle: 'CEO',
    scheduledStartTime: makeVisitIsoTime(11, 45),
    scheduledEndTime: makeVisitIsoTime(12, 30),
    scheduledAt: makeVisitIsoTime(11, 45),
    roomName: 'CEO Executive Chamber',
    building: 'Main Secretariat',
    floor: '2nd Floor',
    subject: 'Campus Recruitment & Industry Academia Partnership',
    purpose: 'High-level discussion on enterprise campus placement drives.',
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'vis-104',
    orgId: 'org-apex-main',
    appointmentId: 'apt-104',
    referenceNo: 'OAMS-2026-00184',
    qrToken: '00184',
    visitorName: 'Priya Nambiar',
    phone: '+91 97112 88410',
    email: 'priya.n@urbaninfra.org',
    organization: 'Urban Infrastructure Directorate',
    idType: 'AADHAAR',
    idLast4: '2104',
    vehicleNo: 'KA 04 MP 5519',
    partySize: 3,
    status: VisitStatus.WITH_HOST,
    badgeNo: 'B-205',
    badgeNumber: 'B-205',
    arrivedAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    checkedInAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    withHostAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    hostOfficialId: 'off-3',
    hostOfficialName: 'VC',
    officialName: 'VC',
    hostOfficialTitle: 'Vice Chancellor',
    scheduledStartTime: makeVisitIsoTime(11, 0),
    scheduledEndTime: makeVisitIsoTime(12, 0),
    scheduledAt: makeVisitIsoTime(11, 0),
    roomName: 'Vice Chancellor Secretariat',
    building: 'Administration Wing',
    floor: '1st Floor',
    subject: 'Joint Research & Smart Campus Grant Review',
    purpose: 'Finalization of Phase 2 laboratory research grant.',
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
  },
  {
    id: 'vis-106',
    orgId: 'org-apex-main',
    appointmentId: 'apt-106',
    referenceNo: 'OAMS-2026-00190',
    qrToken: '00190',
    visitorName: 'Rajeev Saxena',
    phone: '+91 99100 23411',
    email: 'rajeev@solarsolutions.biz',
    organization: 'Solar Tech Vendor',
    idType: 'DRIVING_LICENSE',
    idLast4: '1009',
    partySize: 1,
    status: VisitStatus.DENIED,
    deniedReason: 'Official unavailable; unapproved commercial soliciting at Main Gate.',
    badgeNo: null,
    badgeNumber: null,
    hostOfficialId: 'off-6',
    hostOfficialName: 'Mr. Janardhan',
    officialName: 'Mr. Janardhan',
    hostOfficialTitle: 'Vice Principal / Admin',
    scheduledStartTime: makeVisitIsoTime(10, 0),
    scheduledEndTime: makeVisitIsoTime(10, 30),
    scheduledAt: makeVisitIsoTime(10, 0),
    roomName: 'Chamber 101',
    building: 'Main Secretariat',
    floor: 'Ground Floor',
    subject: 'Solar Panel Maintenance Quotation',
    purpose: 'Commercial quotation submission.',
    createdAt: new Date(Date.now() - 7 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
];

const dNow = new Date();
const from30 = new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString();
const toNow = dNow.toISOString();

export const DEFAULT_REPORTS_OVERVIEW = {
  dateRange: { from: from30, to: toNow },
  kpis: {
    totalAppointments: {
      value: 48,
      unit: 'count',
      formula: 'COUNT(*)',
      description: 'Total official appointment requests processed',
      dateRange: { from: from30, to: toNow },
    },
    avgConfirmTimeMinutes: {
      value: 18.5,
      unit: 'minutes',
      formula: 'AVG(confirmed_at - created_at)',
      description: 'Average time taken from submission to official confirmation',
      dateRange: { from: from30, to: toNow },
    },
    noShowRatePercent: {
      value: 2.1,
      unit: '%',
      formula: '(no_shows / total_confirmed) * 100',
      description: 'Percentage of confirmed attendees who failed to arrive',
      dateRange: { from: from30, to: toNow },
    },
    cancellationRatePercent: {
      value: 3.8,
      unit: '%',
      formula: '(cancelled / total) * 100',
      description: 'Percentage of requested appointments cancelled prior to start',
      dateRange: { from: from30, to: toNow },
    },
    roomUtilizationPercent: {
      value: 74.2,
      unit: '%',
      formula: '(booked_minutes / available_minutes) * 100',
      description: 'Total meeting room booking occupancy across secretariat rooms',
      dateRange: { from: from30, to: toNow },
    },
    slaBreachCount: {
      value: 0,
      unit: 'breaches',
      formula: 'COUNT(sla_breaches)',
      description: 'Requests requiring escalation past standard 24h SLA review time',
      dateRange: { from: from30, to: toNow },
    },
  },
  breakdowns: {
    byStatus: {
      UNDER_REVIEW: 4,
      CONFIRMED: 28,
      IN_PROGRESS: 2,
      CLOSED: 12,
      REJECTED: 2,
    },
    byPriority: {
      LOW: 10,
      MEDIUM: 22,
      HIGH: 12,
      URGENT: 4,
    },
    byOfficial: [
      { officialId: 'off-1', officialName: 'Mr. KVK (Chairman)', count: 24 },
      { officialId: 'off-2', officialName: 'Mr. Harsha Rao (CEO)', count: 18 },
      { officialId: 'off-3', officialName: 'VC (Vice Chancellor)', count: 14 },
      { officialId: 'off-4', officialName: 'Ms. Bharathi (President)', count: 10 },
      { officialId: 'off-5', officialName: 'Ms. Indhu (Joint Secretary)', count: 8 },
      { officialId: 'off-6', officialName: 'Mr. Janardhan (Admin)', count: 6 },
    ],
    roomUtilization: [
      {
        roomId: 'room-1',
        roomName: 'Chamber 101 (Executive Suite)',
        capacity: 10,
        bookedMinutes: 1420,
        utilizationPercent: 82.5,
      },
      {
        roomId: 'room-2',
        roomName: 'Conference Room Alpha',
        capacity: 35,
        bookedMinutes: 1140,
        utilizationPercent: 66.3,
      },
      {
        roomId: 'room-3',
        roomName: 'Committee Room 4',
        capacity: 18,
        bookedMinutes: 1280,
        utilizationPercent: 74.4,
      },
    ],
  },
};

export interface DepartmentItem {
  id: string;
  name: string;
  code: string;
  building: string;
  hodName: string;
  hodEmail: string;
  facultyCount: number;
  studentCount: number;
  createdAt: string;
}

export const INITIAL_DEPARTMENTS: DepartmentItem[] = [
  {
    id: 'dept-1',
    name: 'Computer Science & Engineering',
    code: 'CSE',
    building: 'Academic Block A - Tech Wing',
    hodName: 'Dr. Suresh Babu',
    hodEmail: 'hod.cse@stmarysgroup.com',
    facultyCount: 14,
    studentCount: 380,
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'dept-2',
    name: 'Electronics & Communication',
    code: 'ECE',
    building: 'Academic Block B - Signal Lab',
    hodName: 'Dr. Meenakshi Sundaram',
    hodEmail: 'hod.ece@stmarysgroup.com',
    facultyCount: 11,
    studentCount: 290,
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'dept-3',
    name: 'Mechanical & Aerospace Engineering',
    code: 'MECH',
    building: 'Foundry & Heavy Labs Complex',
    hodName: 'Dr. Rajesh Nair',
    hodEmail: 'hod.mech@stmarysgroup.com',
    facultyCount: 9,
    studentCount: 210,
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'dept-4',
    name: 'Management & Business Studies',
    code: 'MBA',
    building: 'Executive Tower - 4th Floor',
    hodName: 'Prof. Vikram Malhotra',
    hodEmail: 'hod.mba@stmarysgroup.com',
    facultyCount: 8,
    studentCount: 160,
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'dept-5',
    name: 'Academic Affairs & Chancellery',
    code: 'ACAD',
    building: 'Central Secretariat',
    hodName: 'Prof. Vice Chancellor',
    hodEmail: 'vc@stmarysgroup.com',
    facultyCount: 6,
    studentCount: 0,
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'dept-6',
    name: 'Institutional Governance & Protocol',
    code: 'GOV',
    building: 'Executive Chamber & Boardroom',
    hodName: 'Mr. KVK',
    hodEmail: 'kvk@stmarysgroup.com',
    facultyCount: 5,
    studentCount: 0,
    createdAt: '2026-01-15T09:00:00Z',
  },
];

export const INITIAL_USERS = [
  // --- System Administrator ---
  {
    id: 'usr-admin-super',
    fullName: 'System Administrator',
    email: 'admin@stmarysgroup.com',
    designation: 'Chief Administrator & Systems Controller',
    department: 'Central Administration',
    departmentId: 'dept-6',
    status: 'ACTIVE' as const,
    roles: [RoleCode.ADMIN],
  },
  // --- Faculty & Officials ---
  {
    id: 'usr-admin-1',
    fullName: 'Mr. KVK',
    email: 'kvk@stmarysgroup.com',
    designation: 'Chairman & Official',
    department: 'Chamber of Mr. KVK',
    departmentId: 'dept-6',
    status: 'ACTIVE' as const,
    roles: [RoleCode.FACULTY],
  },
  {
    id: 'usr-ceo-1',
    fullName: 'Mr. Harsha Rao',
    email: 'harsha@stmarysgroup.com',
    designation: 'Chief Executive Officer',
    department: 'Office of the Chief Executive Officer',
    departmentId: 'dept-4',
    status: 'ACTIVE' as const,
    roles: [RoleCode.FACULTY],
  },
  {
    id: 'usr-vc-1',
    fullName: 'VC',
    email: 'vc@stmarysgroup.com',
    designation: 'Vice Chancellor & Senior Professor',
    department: 'Office of the Vice Chancellor',
    departmentId: 'dept-5',
    status: 'ACTIVE' as const,
    roles: [RoleCode.FACULTY],
  },
  {
    id: 'usr-bharathi-1',
    fullName: 'Ms. Bharathi',
    email: 'bharathi@stmarysgroup.com',
    designation: 'President',
    department: 'Office of the President',
    departmentId: 'dept-6',
    status: 'ACTIVE' as const,
    roles: [RoleCode.FACULTY],
  },
  // --- Administrative & Support Staff ---
  {
    id: 'usr-indhu-1',
    fullName: 'Ms. Indhu',
    email: 'indhu@stmarysgroup.com',
    designation: 'Joint Secretary & Staff Officer',
    department: 'Secretariat & Directorate',
    departmentId: 'dept-6',
    status: 'ACTIVE' as const,
    roles: [RoleCode.STAFF],
  },
  {
    id: 'usr-janardhan-1',
    fullName: 'Mr. Janardhan',
    email: 'janardhan@stmarysgroup.com',
    designation: 'Vice Principal / Staff Admin',
    department: 'Administration & Security',
    departmentId: 'dept-6',
    status: 'ACTIVE' as const,
    roles: [RoleCode.STAFF],
  },
];

export const INITIAL_HOLIDAYS = [
  {
    id: 'hol-1',
    name: 'Republic Day',
    holidayDate: '2026-01-26',
    isHalfDay: false,
    halfDayPeriod: null,
    description: 'National Holiday',
  },
  {
    id: 'hol-2',
    name: 'Independence Day',
    holidayDate: '2026-08-15',
    isHalfDay: false,
    halfDayPeriod: null,
    description: 'National Holiday',
  },
  {
    id: 'hol-3',
    name: 'Mahatma Gandhi Jayanti',
    holidayDate: '2026-10-02',
    isHalfDay: false,
    halfDayPeriod: null,
    description: 'National Holiday',
  },
  {
    id: 'hol-4',
    name: 'Diwali Festival',
    holidayDate: '2026-11-08',
    isHalfDay: true,
    halfDayPeriod: 'AFTERNOON' as const,
    description: 'Festival Half-Day (Afternoon Session Closed)',
  },
];

export const INITIAL_AUDIT_EVENTS = [
  {
    id: 'aud-1',
    org_id: 'org-apex-main',
    actor_id: 'usr-admin-1',
    actor_role: 'SUPER_ADMIN',
    action: 'appointment.confirmed',
    entity_type: 'appointment',
    entity_id: 'apt-101',
    changes: { status: { from: 'UNDER_REVIEW', to: 'CONFIRMED' } },
    reason: 'Official approved request for Metro Rail review',
    ip_address: '127.0.0.1',
    correlation_id: 'corr-901',
    prev_hash: '0x0000000000000000',
    hash: '0x4f8a9b1c2d3e4f5a6b7c8d9e0f1a2b3c',
    occurred_at: new Date(Date.now() - 3600 * 1000).toISOString(),
  },
  {
    id: 'aud-2',
    org_id: 'org-apex-main',
    actor_id: 'usr-janardhan-1',
    actor_role: 'RECEPTION',
    action: 'visit.checkin',
    entity_type: 'visit',
    entity_id: 'vis-101',
    changes: { status: { from: 'SCHEDULED', to: 'CHECKED_IN' }, badge: 'V-104' },
    reason: 'Attendee arrived at Main Reception gate',
    ip_address: '10.0.4.12',
    correlation_id: 'corr-902',
    prev_hash: '0x4f8a9b1c2d3e4f5a6b7c8d9e0f1a2b3c',
    hash: '0x7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b',
    occurred_at: new Date(Date.now() - 900 * 1000).toISOString(),
  },
  {
    id: 'aud-3',
    org_id: 'org-apex-main',
    actor_id: 'usr-indhu-1',
    actor_role: 'PA',
    action: 'task.created',
    entity_type: 'task',
    entity_id: 'tsk-1',
    changes: { title: 'Review and sign Metro Rail clearance note', priority: 'HIGH' },
    reason: 'Action item created following corridor 3 preparation',
    ip_address: '10.0.2.55',
    correlation_id: 'corr-903',
    prev_hash: '0x7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b',
    hash: '0x9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d',
    occurred_at: new Date(Date.now() - 300 * 1000).toISOString(),
  },
];

export const INITIAL_OPS_OVERVIEW = {
  failedDeliveries: [],
  stuckAppointments: [],
  backgroundJobs: [
    {
      name: 'outboxDispatcher',
      description: 'Dispatches queued outbound email/SMS notification batches',
      schedule: 'Every 1s',
    },
    {
      name: 'taskReminders',
      description: 'Dispatches high-priority reminder alerts for tasks due within 2 hours',
      schedule: 'Every 60s',
    },
    {
      name: 'taskOverdueWorker',
      description: 'Detects overdue tasks and marks escalation flags',
      schedule: 'Every 60s',
    },
    {
      name: 'noShowDetector',
      description: 'Automatically transitions unarrived attendees to NO_SHOW 30 min past slot',
      schedule: 'Every 60s',
    },
    {
      name: 'visitorAutoCheckout',
      description: 'Checks out unclosed visitor passes at close of business (midnight)',
      schedule: 'Every 5m',
    },
    {
      name: 'dailyDigest',
      description: 'Compiles and dispatches morning agenda briefings to officials and PAs',
      schedule: 'Daily at 08:00',
    },
  ],
  syncErrors: [],
};

export const INITIAL_SUPPORT_STAFF = [
  {
    id: 'staff-1',
    officialId: 'off-1',
    userId: 'usr-indhu-1',
    userFullName: 'Ms. Indhu',
    userEmail: 'indhu@stmarysgroup.com',
    roleCode: 'PA',
    canManageCalendar: true,
    canTriageAppointments: true,
    canManageTasks: true,
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-1',
    userId: 'usr-admin-1',
    officialId: 'off-1',
    targetRoles: [RoleCode.FACULTY, RoleCode.STAFF, RoleCode.ADMIN, 'OFFICIAL', 'EA_PA', 'SUPER_ADMIN'],
    type: 'appointment_confirmed',
    eventType: 'appointment_confirmed',
    title: 'Appointment Confirmed (#OAMS-2026-00412)',
    message: 'Appointment with Sanjay Aggarwal (Metro Rail) confirmed. Dual push notification and branded HTML email sent via Microsoft Power Automate.',
    body: 'Appointment with Sanjay Aggarwal (Metro Rail) confirmed. Dual push notification and branded HTML email sent via Microsoft Power Automate.',
    appointmentId: 'apt-101',
    entityType: 'appointment',
    entityId: 'apt-101',
    link: '/app/appointments/apt-101',
    priority: Priority.HIGH,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'usr-admin-1',
    officialId: 'off-1',
    targetRoles: [RoleCode.FACULTY, RoleCode.STAFF, RoleCode.ADMIN, 'OFFICIAL', 'EA_PA', 'SUPER_ADMIN'],
    type: 'appointment_booked',
    eventType: 'appointment_booked',
    title: 'New Urgent Appointment Request (#OAMS-2026-00415)',
    message: 'Dr. Rajiv Sen requested urgent meeting: Cloud Sovereign Data Residency Standard.',
    body: 'Dr. Rajiv Sen requested urgent meeting: Cloud Sovereign Data Residency Standard.',
    appointmentId: 'apt-102',
    entityType: 'appointment',
    entityId: 'apt-102',
    link: '/app/appointments/apt-102',
    priority: Priority.URGENT,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'usr-admin-1',
    officialId: 'off-1',
    targetRoles: [RoleCode.FACULTY, RoleCode.STAFF, RoleCode.RECEPTION, 'OFFICIAL', 'EA_PA', 'RECEPTIONIST'],
    type: 'appointment_reminder',
    eventType: 'appointment_reminder',
    title: 'Appointment Reminder: Upcoming Meeting',
    message: 'Reminder: Scheduled appointment with Rajesh Sharma starts in 30 minutes at Room 302.',
    body: 'Reminder: Scheduled appointment with Rajesh Sharma starts in 30 minutes at Room 302.',
    appointmentId: 'apt-103',
    entityType: 'appointment',
    entityId: 'apt-103',
    link: '/app/appointments/apt-103',
    priority: Priority.HIGH,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-4',
    userId: 'usr-ceo-1',
    officialId: 'off-2',
    targetRoles: [RoleCode.ADMIN, RoleCode.STAFF, RoleCode.FACULTY, 'SUPER_ADMIN', 'EA_PA', 'OFFICIAL'],
    type: 'provider_unavailable',
    eventType: 'provider_unavailable',
    title: 'Official Unavailable: Schedule Adjustment',
    message: 'Dr. K.V. Rao is marked on official duty on Friday. Impacted appointments have been highlighted for rescheduling.',
    body: 'Dr. K.V. Rao is marked on official duty on Friday. Impacted appointments have been highlighted for rescheduling.',
    appointmentId: null,
    entityType: 'official',
    entityId: 'off-1',
    link: '/app/calendar',
    priority: Priority.HIGH,
    isRead: true,
    readAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-5',
    userId: 'usr-admin-1',
    officialId: 'off-1',
    targetRoles: [RoleCode.FACULTY, RoleCode.STAFF, RoleCode.ADMIN, 'OFFICIAL', 'EA_PA', 'SUPER_ADMIN'],
    type: 'appointment_completed',
    eventType: 'appointment_completed',
    title: 'Appointment Completed: Minutes Logged (#OAMS-2026-00398)',
    message: 'Appointment OAMS-2026-00398 with Dept of Telecommunications has been marked completed.',
    body: 'Appointment OAMS-2026-00398 with Dept of Telecommunications has been marked completed.',
    appointmentId: 'apt-104',
    entityType: 'appointment',
    entityId: 'apt-104',
    link: '/app/appointments/apt-104',
    priority: Priority.MEDIUM,
    isRead: true,
    readAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-6',
    userId: 'usr-admin-super',
    targetRoles: ['ALL'],
    type: 'system_alert',
    eventType: 'system_alert',
    title: 'System Notice: Scheduled Maintenance Window',
    message: 'System maintenance scheduled for Sunday 02:00 AM - 04:00 AM IST. All core services will remain uninterrupted.',
    body: 'System maintenance scheduled for Sunday 02:00 AM - 04:00 AM IST. All core services will remain uninterrupted.',
    appointmentId: null,
    entityType: 'system',
    entityId: 'system',
    link: '/app/notifications',
    priority: Priority.LOW,
    isRead: true,
    readAt: new Date(Date.now() - 300 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 360 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-7',
    userId: 'usr-admin-1',
    targetRoles: [RoleCode.SECURITY, RoleCode.ADMIN, 'SUPER_ADMIN'],
    type: 'security_alert',
    eventType: 'security_alert',
    title: 'Security Alert: Gate Pass Mismatch (Main Gate)',
    message: 'Gate Pass mismatch for visitor Rahul Verma at Main Gate. Manual biometric verification requested.',
    body: 'Gate Pass mismatch for visitor Rahul Verma at Main Gate. Manual biometric verification requested.',
    appointmentId: null,
    entityType: 'system',
    entityId: 'system',
    link: '/app/security',
    priority: Priority.URGENT,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  // --- Admin Specific Alerts ---
  {
    id: 'notif-admin-1',
    userId: 'usr-admin-super',
    targetRoles: [RoleCode.ADMIN, 'SUPER_ADMIN', 'APPOINTMENT_ADMIN'],
    type: 'admin_notification',
    eventType: 'SECURITY_AUDIT_LOGGED',
    title: 'System Audit Alert: Privilege Escalation Logged',
    message: 'New support staff assignment and calendar access granted for Chamber of Mr. KVK under §18 compliance standards.',
    body: 'New support staff assignment and calendar access granted for Chamber of Mr. KVK under §18 compliance standards.',
    appointmentId: null,
    entityType: 'audit',
    entityId: 'audit-1',
    link: '/app/audit',
    priority: Priority.HIGH,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-admin-2',
    userId: 'usr-admin-super',
    targetRoles: [RoleCode.ADMIN, 'SUPER_ADMIN', 'APPOINTMENT_ADMIN'],
    type: 'admin_notification',
    eventType: 'SLA_BREACH_WARNING',
    title: 'SLA Warning: 2 Requests Approaching Limit',
    message: '2 appointment requests in Department of Computing have reached 80% SLA elapsed time.',
    body: '2 appointment requests in Department of Computing have reached 80% SLA elapsed time.',
    appointmentId: 'apt-102',
    entityType: 'appointment',
    entityId: 'apt-102',
    link: '/app/appointments',
    priority: Priority.HIGH,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  // --- Faculty / Official Specific Alerts ---
  {
    id: 'notif-fac-1',
    userId: 'usr-admin-1',
    officialId: 'off-1',
    targetRoles: [RoleCode.FACULTY, 'OFFICIAL'],
    type: 'appointment_reminder',
    eventType: 'DAILY_AGENDA_BRIEFING',
    title: 'Daily Schedule Briefing: 3 Sessions Today',
    message: 'You have 3 confirmed meetings today starting at 10:30 AM with Metro Rail, Dept of IT, and Academic Council.',
    body: 'You have 3 confirmed meetings today starting at 10:30 AM with Metro Rail, Dept of IT, and Academic Council.',
    appointmentId: 'apt-101',
    entityType: 'appointment',
    entityId: 'apt-101',
    link: '/app/today',
    priority: Priority.MEDIUM,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-fac-2',
    userId: 'usr-ceo-1',
    officialId: 'off-2',
    targetRoles: [RoleCode.FACULTY, 'OFFICIAL'],
    type: 'appointment_rescheduled',
    eventType: 'RESCHEDULE_ACCEPTED',
    title: 'Reschedule Accepted: AI Ethics Consultation',
    message: 'Dr. Ramesh confirmed the moved time slot for Thursday at 02:00 PM at Boardroom.',
    body: 'Dr. Ramesh confirmed the moved time slot for Thursday at 02:00 PM at Boardroom.',
    appointmentId: 'apt-103',
    entityType: 'appointment',
    entityId: 'apt-103',
    link: '/app/calendar',
    priority: Priority.MEDIUM,
    isRead: true,
    readAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
  },
  // --- Staff / EA / PA Specific Alerts ---
  {
    id: 'notif-staff-1',
    userId: 'usr-indhu-1',
    targetRoles: [RoleCode.STAFF, 'EA_PA', 'PA', 'EA'],
    type: 'system_alert',
    eventType: 'TASK_ASSIGNED',
    title: 'High-Priority Task Assigned: Compile Dossier',
    message: 'New task assigned: Prepare executive dossiers and attendee CVs for Chamber of Mr. KVK review session.',
    body: 'New task assigned: Prepare executive dossiers and attendee CVs for Chamber of Mr. KVK review session.',
    appointmentId: 'apt-101',
    entityType: 'task',
    entityId: 'task-1',
    link: '/app/todo',
    priority: Priority.HIGH,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-staff-2',
    userId: 'usr-janardhan-1',
    targetRoles: [RoleCode.STAFF, 'EA_PA', 'PA', 'EA'],
    type: 'appointment_confirmed',
    eventType: 'VISITOR_WAITING',
    title: 'Visitor Seated: Guest in Executive Lounge',
    message: 'Sanjay Aggarwal (Metro Rail) checked in at front desk and is waiting in the Executive Lounge.',
    body: 'Sanjay Aggarwal (Metro Rail) checked in at front desk and is waiting in the Executive Lounge.',
    appointmentId: 'apt-101',
    entityType: 'appointment',
    entityId: 'apt-101',
    link: '/app/reception',
    priority: Priority.HIGH,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  // --- Reception Specific Alerts ---
  {
    id: 'notif-rec-1',
    userId: 'usr-admin-1',
    targetRoles: [RoleCode.RECEPTION, 'RECEPTIONIST'],
    type: 'appointment_reminder',
    eventType: 'UPCOMING_VISITOR_ARRIVAL',
    title: 'Expected Arrival: Metro Rail Delegation (11:30 AM)',
    message: '4-member delegation arriving for Mr. KVK. Pre-cleared security pass ready for distribution at Front Desk.',
    body: '4-member delegation arriving for Mr. KVK. Pre-cleared security pass ready for distribution at Front Desk.',
    appointmentId: 'apt-101',
    entityType: 'visit',
    entityId: 'visit-1',
    link: '/app/reception',
    priority: Priority.HIGH,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-rec-2',
    userId: 'usr-admin-1',
    targetRoles: [RoleCode.RECEPTION, 'RECEPTIONIST'],
    type: 'security_alert',
    eventType: 'WALK_IN_CHECKIN',
    title: 'Walk-In Registered: Badge B-108 Issued',
    message: 'Walk-in attendee registered for Student Affairs consultation. Waiting in Lobby B.',
    body: 'Walk-in attendee registered for Student Affairs consultation. Waiting in Lobby B.',
    appointmentId: null,
    entityType: 'visit',
    entityId: 'visit-2',
    link: '/app/reception',
    priority: Priority.MEDIUM,
    isRead: true,
    readAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
  },
  // --- Security Specific Alerts ---
  {
    id: 'notif-sec-1',
    userId: 'usr-admin-1',
    targetRoles: [RoleCode.SECURITY],
    type: 'security_alert',
    eventType: 'GATE_CLEARANCE_APPROVED',
    title: 'Vehicle Access: VIP Permit Approved (North Gate)',
    message: 'Vehicle TS-09-EA-2026 cleared for Official Parking Bay 3. Host: Mr. KVK.',
    body: 'Vehicle TS-09-EA-2026 cleared for Official Parking Bay 3. Host: Mr. KVK.',
    appointmentId: null,
    entityType: 'system',
    entityId: 'sec-gate-1',
    link: '/app/security',
    priority: Priority.HIGH,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-sec-2',
    userId: 'usr-admin-1',
    targetRoles: [RoleCode.SECURITY],
    type: 'security_alert',
    eventType: 'BADGE_OVERSTAY_ALERT',
    title: 'Security Notice: Unchecked-Out Visitor Pass',
    message: 'Badge B-319 has exceeded scheduled visit duration by 45 minutes in Wing B. Please follow up.',
    body: 'Badge B-319 has exceeded scheduled visit duration by 45 minutes in Wing B. Please follow up.',
    appointmentId: null,
    entityType: 'system',
    entityId: 'sec-gate-2',
    link: '/app/security',
    priority: Priority.URGENT,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
  },
  // --- Citizen / Requester Specific Alerts ---
  {
    id: 'notif-citizen-1',
    userId: 'usr-admin-1',
    targetRoles: [RoleCode.EMPLOYEE, 'GUEST'],
    type: 'appointment_booked',
    eventType: 'REQUEST_SUBMITTED',
    title: 'Request Status: Under Review (#OAMS-2026-00415)',
    message: 'Your appointment request regarding "Cloud Sovereign Data Residency" has been submitted and is under Secretariat review.',
    body: 'Your appointment request regarding "Cloud Sovereign Data Residency" has been submitted and is under Secretariat review.',
    appointmentId: 'apt-102',
    entityType: 'appointment',
    entityId: 'apt-102',
    link: '/app/appointments/apt-102',
    priority: Priority.MEDIUM,
    isRead: false,
    readAt: null,
    createdAt: new Date(Date.now() - 34 * 60 * 1000).toISOString(),
  },
];

